version: "3"
services:
  db:
    image: "postgres:11"
    container_name: "pg_db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    deploy:
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:

